name: Gradle Package

on:
  release:
    types: [created] # release가 생성될 때

jobs:
  build:
    # Workflow가 실행되는 vm의 OS 지정
    runs-on: ubuntu-latest
    
    # 권한
    permissions:
      contents: read
      packages: write

    steps:
    
    # 1. vm에서 리파지토리를 내려받음
    - uses: actions/checkout@v3
    
    # 2. vm에 jdk를 세팅함
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17' # 버전
        distribution: 'temurin' # 배포판
        server-id: github 
        settings-path: ${{ github.workspace }}
    # 3. gradle build 실행
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: build
    # 4. gradle publish 실행
    # USERNAME, TOKEN 환경 변수에 추가
    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
